# Generated by Django 4.2 on 2023-04-26 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('state', models.CharField(choices=[('NEW', 'NEW'), ('IN PROGRESS', 'IN PROGRESS'), ('CLOSED', 'CLOSED')], default='NEW', max_length=11)),
            ],
        ),
    ]
